export const themeParams = {
  accentColor: 'var(--color-control-bg-primary)',
  advancedFilterBuilderButtonBarBorder:
    'solid var(--control-border-width) var(--color-bg-border)',
  advancedFilterBuilderColumnPillColor: 'var(--color-bg-success)',
  advancedFilterBuilderJoinPillColor: 'var(--color-bg-alert)',
  advancedFilterBuilderOptionPillColor: 'var(--color-bg-warning)',
  advancedFilterBuilderValuePillColor: 'var(--color-bg-normal)',
  backgroundColor: 'var(--color-bg-default)',
  borderColor: 'var(--color-bg-border)',
  borderRadius: 'var(--control-radius)',
  cellHorizontalPadding: 'var(--space-m)',
  cellHorizontalPaddingScale: 1,
  cellTextColor: 'var(--color-typo-primary)',
  cellWidgetSpacing: 'var(--space-m)',
  chartMenuLabelColor:
    'color-mix(in srgb, transparent, var(--ag-foreground-color) 80%)',
  chartMenuPanelWidth: '260px',
  chromeBackgroundColor: 'var(--color-bg-default)',
  // columnBorder: 'solid var(--control-border-width) var(--ag-border-color)', // не входит в основной состав темы
  columnDropCellBackgroundColor:
    'color-mix(in srgb, transparent, var(--ag-foreground-color) 90%)',
  columnDropCellTextColor: 'var(--ag-text-color)',
  columnDropCellDragHandleColor: 'var(--ag-text-color)',
  columnDropCellBorder:
    'solid var(--control-border-width) var(--ag-border-color)',
  columnHoverColor:
    'color-mix(in srgb, transparent, var(--ag-accent-color) 5%)',
  columnSelectIndentSize: 'var(--ag-icon-size)',
  dialogBorder: 'solid var(--control-border-width) var(--ag-border-color)',
  dialogShadow: 'var(--shadow-modal)',
  cellEditingBorder: 'solid var(--control-border-width) var(--ag-border-color)',
  cellEditingShadow: 'var(--ag-card-shadow)',
  dragAndDropImageBackgroundColor: 'var(--ag-background-color)',
  dragAndDropImageBorder:
    'solid var(--control-border-width) var(--ag-border-color)',
  dragAndDropImageShadow: 'var(--shadow-group)',
  dragHandleColor:
    'color-mix(in srgb, transparent, var(--ag-foreground-color) 70%)',
  dropdownShadow: 'var(--shadow-layer)',
  filterToolPanelGroupIndent: 'var(--ag-spacing)',
  focusShadow: 'var(--shadow-group)',
  fontFamily: 'var(--font-primary)',
  fontSize: 'var(--size-text-s)',
  dataFontSize: 'var(--ag-font-size)',
  footerRowBorder: 'var(--ag-row-border)',
  foregroundColor: 'var(--color-typo-primary)',
  spacing: 'var(--space-xs)',
  headerBackgroundColor: 'var(--color-bg-secondary)',
  headerCellBackgroundTransitionDuration: '0.2s',
  headerCellHoverBackgroundColor: 'transparent',
  headerCellMovingBackgroundColor: 'transparent',
  headerColumnBorder: 'none',
  headerColumnBorderHeight: '100%',
  headerColumnResizeHandleColor: 'var(--color-bg-border)',
  headerColumnResizeHandleHeight: '30%',
  headerColumnResizeHandleWidth: 'var(--control-border-width)',
  headerFontFamily: 'var(--ag-font-family)',
  cellFontFamily: 'var(--ag-font-family)',
  headerFontSize: 'var(--ag-font-size)',
  headerFontWeight: 'var(--font-weight-text-medium)',
  headerHeight:
    'calc(max(var(--ag-icon-size), var(--ag-data-font-size)) + var(--ag-spacing) * 4 * var(--ag-header-vertical-padding-scale))',
  headerRowBorder: 'solid var(--control-border-width) var(--ag-border-color)',
  headerTextColor: 'var(--color-typo-secondary)',
  headerVerticalPaddingScale: 1,
  iconButtonHoverBackgroundColor: 'var(--color-control-bg-clear-hover)',
  iconButtonHoverColor: 'var(--color-control-typo-clear-hover)',
  iconSize: 'var(--graphics-size-s)',
  invalidColor: 'var(--color-bg-alert)',
  listItemHeight:
    'calc(var(--ag-icon-size) + var(--ag-widget-vertical-spacing))',
  menuBackgroundColor:
    'color-mix(in srgb, var(--ag-background-color), var(--ag-foreground-color) 3%)',
  menuBorder: 'solid var(--control-border-width) var(--ag-border-color)',
  menuSeparatorColor: 'var(--ag-border-color)',
  menuShadow: 'var(--ag-popup-shadow)',
  menuTextColor:
    'color-mix(in srgb, var(--ag-background-color), var(--ag-foreground-color) 95%)',
  modalOverlayBackgroundColor:
    'color-mix(in srgb, transparent, var(--ag-background-color) 66%)',
  //   oddRowBackgroundColor: 'var(--color-bg-stripe)', // не входит в основной состав темы
  panelBackgroundColor: 'var(--ag-background-color)',
  panelTitleBarBackgroundColor: 'var(--ag-header-background-color)',
  panelTitleBarBorder:
    'solid var(--control-border-width) var(--ag-border-color)',
  pinnedColumnBorder:
    'solid var(--control-border-width) var(--ag-border-color)',
  pinnedRowBorder: 'solid var(--control-border-width) var(--ag-border-color)',
  popupShadow: 'var(--shadow-modal)',
  cardShadow: 'var(--shadow-layer)',
  rangeSelectionBackgroundColor:
    'color-mix(in srgb, transparent, var(--ag-accent-color) 20%)',
  rangeSelectionBorderColor: 'var(--ag-accent-color)',
  rangeSelectionBorderStyle: 'solid',
  rangeSelectionChartBackgroundColor: '#0058ff1a',
  rangeSelectionChartCategoryBackgroundColor: '#00ff841a',
  rangeSelectionHighlightColor:
    'color-mix(in srgb, transparent, var(--ag-accent-color) 50%)',
  rowBorder: 'solid var(--control-border-width) var(--ag-border-color)',
  rowGroupIndentSize:
    'calc(var(--ag-cell-widget-spacing) + var(--ag-icon-size))',
  rowHeight:
    'calc(max(var(--ag-icon-size), var(--ag-data-font-size)) + var(--ag-spacing) * 3.25 * var(--ag-row-vertical-padding-scale))',
  rowHoverColor: 'color-mix(in srgb, transparent, var(--ag-accent-color) 15%)',
  rowLoadingSkeletonEffectColor:
    'color-mix(in srgb, transparent, var(--ag-foreground-color) 15%)',
  rowVerticalPaddingScale: 1,
  selectCellBackgroundColor:
    'color-mix(in srgb, transparent, var(--ag-foreground-color) 7%)',
  selectCellBorder: 'solid var(--control-border-width) var(--ag-border-color)',
  selectedRowBackgroundColor:
    'color-mix(in srgb, transparent, var(--ag-accent-color) 20%)',
  setFilterIndentSize: 'var(--ag-icon-size)',
  sideBarBackgroundColor: 'var(--ag-chrome-background-color)',
  sideButtonBarBackgroundColor: 'var(--ag-side-bar-background-color)',
  sideBarPanelWidth: '250px',
  sidePanelBorder: 'solid var(--control-border-width) var(--ag-border-color)',
  sideButtonBarTopPadding: '0px',
  sideButtonSelectedUnderlineWidth: 'var(--space-3xs)',
  sideButtonSelectedUnderlineColor: 'transparent',
  sideButtonSelectedUnderlineTransitionDuration: '0s',
  sideButtonBackgroundColor: 'transparent',
  sideButtonTextColor: 'var(--ag-text-color)',
  sideButtonHoverBackgroundColor: 'var(--ag-side-button-background-color)',
  sideButtonHoverTextColor: 'var(--ag-side-button-text-color)',
  sideButtonSelectedBackgroundColor: 'var(--ag-background-color)',
  sideButtonSelectedTextColor: 'var(--ag-side-button-text-color)',
  sideButtonSelectedBorder:
    'solid var(--control-border-width) var(--ag-border-color)',
  sideButtonLeftPadding: 'var(--ag-spacing)',
  sideButtonRightPadding: 'var(--ag-spacing)',
  sideButtonVerticalPadding: 'calc(var(--ag-spacing) * 3)',
  subtleTextColor: 'var(--color-typo-secondary)',
  textColor: 'var(--ag-foreground-color)',
  toggleButtonWidth: 'var(--control-height-xs)',
  toggleButtonHeight:
    'calc(var(--ag-toggle-button-width) / 2 + var(--space-3xs))',
  toggleButtonOffBackgroundColor:
    ' color-mix(in srgb, var(--ag-background-color), var(--ag-foreground-color) 30%)',
  toggleButtonOnBackgroundColor: ' var(--ag-accent-color)',
  toggleButtonSwitchBackgroundColor: 'var(--ag-background-color)',
  toggleButtonSwitchInset: 'var(--space-3xs)',
  toolPanelSeparatorBorder:
    'solid var(--control-border-width) var(--ag-border-color)',
  tooltipBackgroundColor: 'var(--ag-chrome-background-color)',
  tooltipBorder: 'solid var(--control-border-width) var(--ag-border-color)',
  tooltipTextColor: 'var(--ag-text-color)',
  valueChangeDeltaDownColor: '#e53935',
  valueChangeDeltaUpColor: '#43a047',
  valueChangeValueHighlightBackgroundColor: '#16a08580',
  widgetContainerHorizontalPadding: 'calc(var(--ag-spacing) * 1.5)',
  widgetContainerVerticalPadding: 'calc(var(--ag-spacing) * 1.5)',
  widgetHorizontalSpacing: 'calc(var(--ag-spacing) * 1.5)',
  widgetVerticalSpacing: 'var(--ag-spacing)',
  wrapperBorder: 'none',
  wrapperBorderRadius: 'none',
  checkboxBorderRadius: 'var(--control-radius)',
  checkboxBorderWidth: 'var(--control-border-width)',
  checkboxCheckedBackgroundColor: 'var(--color-control-bg-primary)',
  checkboxCheckedBorderColor: 'var(--color-control-bg-primary)',
  checkboxCheckedShapeColor: 'var(--color-control-typo-primary)',
  checkboxIndeterminateBackgroundColor: 'var(--color-control-bg-primary)',
  checkboxIndeterminateBorderColor: 'var(--color-control-bg-primary)',
  checkboxIndeterminateShapeColor: 'var(--color-control-typo-primary)',
  checkboxUncheckedBackgroundColor: ' var(--ag-background-color)',
  checkboxUncheckedBorderColor:
    'color-mix(in srgb,var(--ag-background-color),var(--ag-foreground-color) 30%)',
  tabBarBorder: 'solid var(--control-border-width) var(--ag-border-color)',
  tabBarBackgroundColor:
    'color-mix(in srgb, transparent, var(--ag-foreground-color) 5%)',
  tabTextColor: 'color-mix(in srgb, transparent, var(--ag-text-color) 70%)',
  tabSelectedTextColor: 'var(--ag-text-color)',
  tabHoverTextColor: 'var(--ag-text-color)',
  tabSelectedBorderColor: 'var(--ag-border-color)',
  tabSelectedBackgroundColor: 'var(--ag-background-color)',
  tabBackgroundColor: 'transparent',
  tabBarHorizontalPadding: '0px',
  tabBarTopPadding: '0px',
  tabBottomPadding: 'var(--ag-spacing)',
  tabHorizontalPadding: 'var(--ag-spacing)',
  tabHoverBackgroundColor: 'var(--ag-tab-background-color)',
  tabSelectedBorderWidth: 'var(--control-border-width)',
  tabSelectedUnderlineColor: 'transparent',
  tabSelectedUnderlineTransitionDuration: '0s',
  tabSelectedUnderlineWidth: '0px',
  tabSpacing: '0',
  tabTopPadding: 'var(--ag-spacing)',
  inputBackgroundColor: 'var(--ag-background-color)',
  inputBorder:
    'solid var(--control-border-width) var(--color-control-bg-border-default)',
  inputBorderRadius: 'var(--ag-border-radius)',
  inputPaddingStart: 'var(--ag-spacing)',
  inputFocusBorder:
    'solid var(--control-border-width) var(--color-control-bg-border-focus)',
  inputFocusShadow: 'var(--shadow-layer)',
  inputDisabledBackgroundColor: 'var(--color-control-bg-disable)',
  inputDisabledTextColor: 'var(--color-control-typo-disable)',
  inputInvalidBorder:
    'solid var(--control-border-width) var(--ag-invalid-color)',
  inputDisabledBorder: 'transparent',
  inputFocusBackgroundColor: 'var(--color-control-bg-default)',
  inputFocusTextColor: 'var(--ag-input-text-color)',
  inputHeight:
    'calc(max(var(--ag-icon-size), var(--ag-font-size)) + var(--ag-spacing) * 2)',
  inputInvalidBackgroundColor: 'var(--ag-input-background-color)',
  inputInvalidTextColor: 'var(--ag-input-text-color)',
  inputTextColor: 'var(--color-control-typo-default)',
  inputPlaceholderTextColor: 'var(--field-control-layout-placeholder-color)',
  inputIconColor: 'var(--ag-input-text-color)',
} as const;
